# Generated by Django 4.0.5 on 2022-06-02 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('users', '0002_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='character_pics')),
                ('name', models.CharField(max_length=50)),
                ('stats', models.OneToOneField(on_delete=models.CASCADE, to='users.Stats')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=models.DO_NOTHING, to='users.Profile')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
