# Generated by Django 4.0.5 on 2022-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True)),
                ('characters', models.ManyToManyField(to='users.character')),
                ('is_waiting', models.BooleanField()),
                ('info_json', models.CharField(max_length=512, default="{}")),
            ],
        ),
    ]
