# Generated by Django 5.0.8 on 2024-08-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.ForeignKey(to='chat.scenario', on_delete=models.CASCADE)),
                ('content', models.CharField(max_length=256)),
                ('is_final', models.BooleanField(default=False))
            ],
        ),
    ]
