# Generated by Django 5.0.8 on 2024-08-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_scenariopart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioFightState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_info', models.CharField(max_length=256)),
                ('health', models.IntegerField()),
                ('monster_class', models.IntegerField()),
                ('cube_class', models.IntegerField()),
            ],
        ),
    ]
