# Generated by Django 5.0.8 on 2024-08-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_scenariofightstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.OneToOneField(to='chat.scenario', on_delete=models.CASCADE)),
                ('current_part', models.OneToOneField(to='chat.scenariopart', on_delete=models.CASCADE)),
                ('fight_state', models.OneToOneField(to='chat.scenariofightstate', on_delete=models.CASCADE, null=True, blank=True)),
            ],
        ),
    ]
